version: "3.8"

services:
  # region Production App
  app:
    container_name: mini-feeds-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - APP_NAME=Mini Feeds API
      - HOST=0.0.0.0
      - PORT=3000
      - JWT_SECRET=supersecret
      - DATABASE_URL=postgresql://root:rootpassword@db:5432/mini-feeds-db?schema=public
    depends_on:
      - db
    networks:
      - app-network

  # region Database
  db:
    image: postgres:15-alpine
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: mini-feeds-db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
