import { Router } from 'express';
import { UserController } from '../controllers';
import AuthMiddleware from '../middlewares/auth.middleware';

const router: Router = Router();
const userController = new UserController();

/**
 * @swagger
 * tags:
 *   name: Users
 *   description: User profile and management
 */

/**
 * @swagger
 * /users/profile:
 *   get:
 *     summary: Get current authenticated user profile
 *     tags: [Users]
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: User profile retrieved successfully
 *       401:
 *         description: Unauthorized
 */
// region GET - /users/profile
router.get('/profile', AuthMiddleware.verifyUser, userController.getProfile);

/**
 * @swagger
 * /users/fcm-token:
 *   post:
 *     summary: Update user's FCM token for notifications
 *     tags: [Users]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - fcmToken
 *             properties:
 *               fcmToken:
 *                 type: string
 *                 description: The FCM token generated by the mobile app
 *     responses:
 *       200:
 *         description: FCM token updated successfully
 *       400:
 *         description: FCM token is required
 *       401:
 *         description: Unauthorized
 */
// region POST - /users/fcm-token
router.post('/fcm-token', AuthMiddleware.verifyUser, userController.updateFcmToken);

/**
 * @swagger
 * /users/notifications:
 *   get:
 *     summary: Get all notifications for current authenticated user
 *     tags: [Users]
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: Notifications retrieved successfully
 *       401:
 *         description: Unauthorized
 */
// region GET - /users/notifications
router.get('/notifications', AuthMiddleware.verifyUser, userController.getNotifications);

export default router;
